I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script call
    call scene_2
  File "game/story/Act2/scene_2.rpy", line 146, in script call
    call scene_3_1
  File "game/story/Act2/scene_3_1.rpy", line 97, in script
    with Shake
  File "game/story/Act2/scene_3_1.rpy", line 97, in <module>
    with Shake
NameError: name 'Shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script call
    call scene_2
  File "game/story/Act2/scene_2.rpy", line 146, in script call
    call scene_3_1
  File "game/story/Act2/scene_3_1.rpy", line 97, in script
    with Shake
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/story/Act2/scene_3_1.rpy", line 97, in <module>
    with Shake
NameError: name 'Shake' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Echoes Beyond The Gate 1.0
Thu Nov  9 20:31:25 2023
